### ISSUE TITLE
performance issue with lots of data

### ISSUE THREAD

**Issue by Archelyst** [seebass/django-rest-hal#2]
I have requests that generate responses with thousands of objects. Such a request easily takes more than 5 seconds. I profiled it and found that a huge chunk of the time is used to generate the links.

Hence, it would be nice to have an option to disable links. That would also decrease the response size drastically.

**Comment by seebass** [comment]
Hope that helps boosting your performance :D 

https://github.com/seebass/django-rest-hal/commit/d667d82c3b679a2133638271cae08861f84d4411

**Comment by Tim-Erwin** [comment]
Works like a charm, thanks to much! :)
